package com.myspace.space_136519;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ValidationErrorDO implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public ValidationErrorDO() {
    }




}